version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./server/data:/app/server/data"
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3000:80"
