# Generated by Django 3.2 on 2021-04-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('start_data', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
