export const QUERY_BY_PHONE = 'QUERY_BY_PHONE'
export const QUERY_BY_NAME = 'QUERY_BY_NAME'
export const EXTEND_LICENSE_DURATION = 'EXTEND_LICENSE_DURATION'
export const TERMINATE_LICENSE = 'TERMINATE_LICENSE'